routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();


Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/users', 'admin\UsersController');
    Route::resource('/admins', 'admin\AdminsController');
    Route::resource('/deliveries', 'admin\DeliveriesController');
    Route::resource('/contacts', 'admin\ContactsController');
    Route::get('/contact/{id}/reply', 'admin\ContactsController@reply');
    Route::post('/contact/{id}/sendreply', 'admin\ContactsController@sendReply');
    Route::resource('/settings', 'admin\SettingController');
    Route::resource('/categories', 'admin\CategoriesController');
    Route::resource('/sliders', 'admin\SlidersController');
    Route::resource('/stores', 'admin\StoresController');
    Route::resource('/coupons', 'admin\CouponsController');
    Route::resource('/orders', 'admin\OrdersController');
    Route::resource('/offers', 'admin\OffersController');
    Route::resource('/invoices', 'admin\InvoicesController');
});




Route::get('mandoub/{user_id?}', 'UsersController@mandoub')->name('mandoub');
Route::post('signupDelegation', 'UsersController@signupDelegation')->name('signupDelegation');

Route::get('signup-succeed', 'UsersController@signupSucceed')->name('signupSucceed');

app/Models/Offer.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{
    protected $table = 'offers';
    protected $guarded = [];

    public $timestamps = true;

    public function order()
    {
        return $this->belongsTo(Order::class, 'order_id');
    }
    public function captain()
    {
        return $this->belongsTo(User::class, 'captain_id');
    }
    public function invoice()
    {
        return $this->hasOne(Invoice::class, 'offer_id');
    }
}

app/Http/Controllers/Api/OffersController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\RateRequest;
use App\Http\Requests\UserRateRequest;
use App\Http\Resources\CaptainRatesCollection;
use App\Http\Resources\OfferCollection;
use App\Http\Resources\Order;
use App\Http\Resources\UserRatesCollection;
use App\Models\Captain_rate;
use App\Models\Offer;
use App\Models\SavedAdress;
use App\Models\User_rates;
use App\Notifications\AcceptOfferDeliveryNotification;
use App\Notifications\NewOfferDeliveryNotification;
use App\Notifications\RefurseOfferDeliveryNotification;
use App\User;
use Helpers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Notification;

class OffersController extends Controller
{
    public function acceptOffer($id)
    {
        if (Helpers::CheckAuthorizedRequest() == null)
            return response()->json(['error' => 'unauthorized'], 401);

        $user = Helpers::getLoggedUser();
        if (!$user || $user == 'No results') {
            return response()->json(['error' => Helpers::failFindId()], 400);
        }
        $offer = Offer::where('id', $id)->first();
        $offer_ids = Offer::where('order_id', $offer->order->id)->pluck('id');
        if (count($offer_ids) > 0) {
            foreach ($offer_ids as $offer_id) {
                $other_offer = Offer::find($offer_id);
                $other_offer->update(['status' => 'Rejected']);
            }
        }
        $offer->update(['status' => 'Accepted']);
        $offer->order->update(['status' => 'InProgress']);
        $captain = User::where('id', $offer->captain_id)->select(['id', 'name', 'photo', 'phone', 'latitude', 'langitude', 'device_token'])->first();
        $captain['delivary_cost'] = $offer->delivary_cost;


        //notification
        $title = 'تدلل';
        $content = 'تقديم عرض سعر';
        $message = [
            'type' => 'accept_offer',
            "offer_id" => (int)$offer->id,
            "user_id" => (int)$offer->order->user_id,
        ];
        Notification::send($offer->captain, new AcceptOfferDeliveryNotification($offer));
        \Helpers::fcm_notification($captain->device_token, $content, $title, $message);


        return response()->json(['order' => new Order($offer->order), 'captain' => $captain, 'offer_id' => $offer->id], 200);
    }

    /**
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function allOffers($id)
    {
        if (Helpers::CheckAuthorizedRequest() == null)
            return response()->json(['error' => 'unauthorized'], 401);

        $user = Helpers::getLoggedUser();
        if (!$user || $user == 'No results') {
            return response()->json(['error' => Helpers::failFindId()], 400);
        }
        $offers = Offer::where('order_id', $id)->get();
        return response()->json(['offers' => new OfferCollection($offers)], 200);
    }

    public function rejectOffer($id)
    {

        if (Helpers::CheckAuthorizedRequest() == null)
            return response()->json(['error' => 'unauthorized'], 401);

        $user = Helpers::getLoggedUser();
        if (!$user || $user == 'No results') {
            return response()->json(['error' => Helpers::failFindId()], 400);
        }
        $offer = Offer::find($id);

        $offer->update([
            'status' => 'Rejected'
        ]);

        //notification
        $title = 'تدلل';
        $content = 'رفض عرض سعر';
        $message = [
            'type' => 'reject_offer',
            "offer_id" => (int)$id,
        ];
        Notification::send($offer->captain, new RefurseOfferDeliveryNotification($offer));
        \Helpers::fcm_notification($offer->captain->device_token, $content, $title, $message);

        return response()->json([], 204);
    }

    public function cancelOffer($id)
    {
        if (Helpers::CheckAuthorizedRequest() == null)
            return response()->json(['error' => 'unauthorized'], 401);

        $user = Helpers::getLoggedUser();
        if (!$user || $user == 'No results') {
            return response()->json(['error' => Helpers::failFindId()], 400);
        }
        Offer::where('id', $id)->delete();

        return response()->json([], 204);
    }

    /**
     * @param RateRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function rateCaptain(RateRequest $request)
    {
        $user = \Helpers::getLoggedUser();
        if (!$user || $user == 'No results') {
            return response()->json(['error' => \Helpers::failFindId()], 400);
        }
        Captain_rate::create([
            'user_id' => $user->id,
            'captain_id' => $request->captain_id,
            'degree' => $request->degree,
            'comment' => $request->comment,
        ]);
        return response()->json([], 204);
    }

    /**
     * @param UserRateRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function rateUser(UserRateRequest $request)
    {
        $user = \Helpers::getLoggedUser();
        if (!$user || $user == 'No results') {
            return response()->json(['error' => \Helpers::failFindId()], 400);
        }
        User_rates::create([
            'user_id' => $request->user_id,
            'captain_id' => $user->id,
            'degree' => $request->degree,
            'comment' => $request->comment,

        ]);
        return response()->json([], 204);
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function sendOffer(Request $request)
    {
        $user = \Helpers::getLoggedUser();
        if (!$user || $user == 'No results') {
            return response()->json(['error' => \Helpers::failFindId()], 400);
        }
        $offer = Offer::create([
            'order_id' => $request->order_id,
            'captain_id' => $user->id,
            'delivary_cost' => $request->delivary_cost,
            'status' => 'Pending',
        ]);

        $rates = User_rates::where('captain_id', $offer->captain_id);
        if ($offer->order->address_id) {
            $address = SavedAdress::find($offer->order->address_id);
            $delivery_point_latitude = (double)$address->latitude;
            $delivery_point_longitude = (double)$address->langitude;
        } else {
            $delivery_point_latitude = (double)$offer->order->delivary_point_latitude;
            $delivery_point_longitude = (double)$offer->order->delivary_point_langitude;
        }
        //notification
        $title = 'تدلل';
        $content = 'تقديم عرض سعر';
        $message = [
            'type' => 'offer',
            "offer_id" => (int)$offer->id,
            "order_id" => (int)$offer->order->id,
            "order_number" => (int)$offer->order->order_number,
            "captain_id" => (int)$offer->captain->id,
            "captain_name" => $offer->captain->name ?: "",
            "captain_image" => Helpers::base_url() . $offer->captain->photo ?: "",
            "captain_rate" => (float)$rates->avg('degree') ?: 0,
            "rate_count" => $rates->count() ?: 0,
            "captain_latitude" => (double)$offer->captain->latitude ?: 0,
            "captain_longitude" => (double)$offer->captain->langitude ?: 0,
            "delivery_point_latitude" => $delivery_point_latitude,
            "delivery_point_longitude" => $delivery_point_longitude,
            "delivery_time" => $offer->order->delivary_time ?: "",
            "delivery_cost" => (double)$offer->delivary_cost ?: 0,
        ];
        Notification::send($offer->order->user, new NewOfferDeliveryNotification($offer));
        \Helpers::fcm_notification($offer->order->user->device_token, $content, $title, $message);

        return response()->json([], 204);
    }

    //تقييمات المناديب للعملاء
    public function getCaptainsRates($id)
    {
        $rates = User_rates::where('user_id', $id)->get();
        return response()->json(['rates' => new UserRatesCollection($rates)], 200);
    }

    //تقييمات المستخدمين للمناديب
    public function getUsersRates($id)
    {
        $rates = Captain_rate::where('captain_id', $id)->get();
        return response()->json(['rates' => new CaptainRatesCollection($rates)], 200);
    }
}

app/Http/Controllers/admin/OffersController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Offer;
use Illuminate\Http\Request;

class OffersController extends Controller
{
    public function index()
    {
        $offers=Offer::orderBy('created_at','ASC')->paginate(10);
        return view('admin.offers.index',compact('offers'));
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $offer=Offer::find($id);
        return view('admin.offers.show',compact('offer'));

    }


    public function destroy($id)
    {
        Offer::destroy($id);
        return redirect('/webadmin/offers')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم حذف العرض بنجاح']));

    }
}

resources/views/admin/offers/index.blade.php
@extends('admin.layouts.app')
@section('title')
    العروض
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item active-top-bar">
        <a href="javascript:;" class="m-menu__link">
            <span class="m-menu__link-text">العروض</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>

@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        العروض
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            {{--<div><a href="{{route('offers.create')}}" style="margin-bottom:20px"--}}
                    {{--class="btn btn_primary btn btn-danger"><i class=" fa fa-edit"></i> اضف كوبون</a></div>--}}


            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_country">
                <thead>
                <tr>
                    <th>#</th>
                    <th>سعر التوصيل</th>
                    <th>الطلب</th>
                    <th> المندوب</th>
                    <th>الحاله</th>
                    <th>الاجراءات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($offers as $index=>$offer)
                    <tr>
                        <td>{{$index + $offers->firstItem()}}</td>
                        <td>{{$offer->delivary_cost}}</td>
                        <td><a href="/webadmin/orders/{{$offer->order_id}}">{{$offer->order->order_number}}</a></td>
                        <td>{{$offer->captain->name}}</td>
                        <td>{{$offer->status}}</td>
                        <td>
                            {{--<a title="عرض التفاصيل" href="/webadmin/offers/{{$offer->id}}"><i--}}
                                    {{--class="fa fa-eye"></i></a>--}}
                            <form class="inline-form-style"
                                  action="/webadmin/offers/{{ $offer->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete"/>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            {{$offers->links()}}
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/countrcountriess!!}--}}
@endsection